server:
  port: 8388

sftp:
  # 端口
  port: 22
  # 服务器地址
  host: 10.10.120.71
  # 账号
  userName: taxctrl
  # 密码
  password: taxctrl
  # 文件存储的根路径
  basePath: /home/taxctrl/test
  # session连接超时时间
  sessionConnectTimeout: 30000
  # channel连接超时时间
  channelConnectedTimeout: 30000
  # 协议
  protocol: sftp
